name: ArenaCreator
main: de.rexlmanu.mlgrush.arenacreator.ArenaCreatorPlugin
version: @version@
author: @author@
description: @description@
website: @website@
commands:
  arenacreator:
    aliases: ac
    usage: /arenacreator help
    description: Tool to create arenas for mlgrush
    permission: mlgrush.command.arenacreator